name: seq2seq

train_data_path: data/ted_dataset/lmdb_train
val_data_path: data/ted_dataset/lmdb_val
test_data_path: data/ted_dataset/lmdb_test

wordembed_dim: 300
wordembed_path: data/fasttext/crawl-300d-2M-subword.bin

model_save_path: output/train_seq2seq
random_seed: -1

# model params
model: seq2seq
mean_dir_vec: [ 0.0154009, -0.9690125, -0.0884354, -0.0022264, -0.8655276, 0.4342174, -0.0035145, -0.8755367, -0.4121039, -0.9236511, 0.3061306, -0.0012415, -0.5155854,  0.8129665,  0.0871897, 0.2348464,  0.1846561,  0.8091402,  0.9271948,  0.2960011, -0.013189 ,  0.5233978,  0.8092403,  0.0725451, -0.2037076, 0.1924306,  0.8196916]
mean_pose: [ 0.0000306,  0.0004946,  0.0008437,  0.0033759, -0.2051629, -0.0143453,  0.0031566, -0.3054764,  0.0411491,  0.0029072, -0.4254303, -0.001311 , -0.1458413, -0.1505532, -0.0138192, -0.2835603,  0.0670333,  0.0107002, -0.2280813,  0.112117 , 0.2087789,  0.1523502, -0.1521499, -0.0161503,  0.291909 , 0.0644232,  0.0040145,  0.2452035,  0.1115339,  0.2051307]
hidden_size: 200
n_layers: 2
dropout_prob: 0.1
z_type: none

# train params
epochs: 100
batch_size: 128
learning_rate: 0.0001
loss_regression_weight: 250
loss_kld_weight: 0.1  # weight for continuous motion term
loss_reg_weight: 25  # weight for motion variance term

# eval params
eval_net_path: output/train_h36m_gesture_autoencoder/gesture_autoencoder_checkpoint_best.bin

# dataset params
motion_resampling_framerate: 15
n_poses: 34
n_pre_poses: 4
subdivision_stride: 10
loader_workers: 3
